#
debug: true

coin:
  gaming:
    api:
      onetouch:
        url: ${ONE_TOUCH_BASE_URL:https://test-platform.onetouch.io/api}
        game_path: ${ONE_TOUCH_GAME_PATH:/operator/generic/v2/game/url}
    retry:
      game_url:
        max_attempts: ${GAME_URL_RETRY_MAX_ATTEMPTS:3}
        timeout: ${GAME_URL_RETRY_TIMEOUT:30000}
    cert:
      # we can put our files outside application
      private_key: ${CERT_PRIVATE_KEY_FILENAME:ssl/private_test_task.pem}
      public_key: ${CERT_PUBLIC_KEY_FILENAME:ssl/public_test_task.pem}}

feign:
  compression:
    request:
      enabled: true
    retxsponse:
      enabled: true
      useGzipDecoder: true
  httpclient:
    disable-ssl-validation: false
  client:
    config:
      # ?????? default: ? ?? ??? ???? ~ ????? ??????????? ??? ??????????? ????? ??????? ???? ?????????
      default:
        # FULL | BASIC | HEADERS | NONE ~ ?? ????? ??????????????
        loggerLevel: FULL
        connectTimeout: 5000
        readTimeout: 5000

# swagger-ui custom path
springdoc:
  packagesToScan: coin.gaming
  swagger-ui:
    path: /swagger-ui.html
    # Disabling the swagger-ui
    enabled: true
  api-docs:
    path: /api-docs
    # Disabling the /v3/api-docs enpoint
    enabled: true

spring:
  devtools:
    add-properties: ${SRPING_DEV_TOOLS:true}

  application:
    name: coing-gaming-demo

server:
  port: ${PORT:8123}
